import 'package:flutter/material.dart';

class AppColors {
  AppColors._();

  static Color primaryColor = const Color(0xff01B091);
  static Color backgroundGreenColor = const Color(0xffD8F0E7);
  static Color greyColor = const Color(0xff4B5C6B);
  static Color lightGreenColor = const Color(0xff94E3CA);
  static Color pinkColor = const Color(0xffFE4A78);
  static Color promoPinkColor = const Color(0xffFFC7DA);
  static Color lightRed = const Color(0xffF9C9CA);
  static Color appBarRedColor = const Color(0xffFF5A5E);
  static Color darkBlue = const Color(0xff111e71);
  static Color brightYellow = const Color(0xffF8DE30);
  static Color yellow = const Color(0xffFFC72F);
  static Color cyan = const Color(0xff479F9E);
  static Color accentColor = const Color(0xff068E76);
  static Color disabledColor = const Color(0xffBBC0BF);
  static Color successColor = const Color(0xff51AB66);
  static Color errorColor = const Color(0xffB3261E);
  static Color textGreyColor = const Color(0xff6F6675);
  static Color subHeadlineTextColor = const Color(0xff615F5F);
  static Color headlineTextColor = const Color(0xff062822);
  static Color textLightColor = const Color(0xffA7A8A8);
  static Color outlinedTextColor = const Color(0xffE6E7E6);
  static Color onBoardingSliderIndicatorInActiveColor = const Color(0x40E6E7E6);
  static Color separatorTextColor = const Color(0xffECECEC);
  static Color componentBackgroundColor = const Color(0xffEEF2F2);
  static Color backgroundColor = const Color(0xffF8FDFC);
  static Color containerBackGroundColor = const Color(0xffF5FAFA);
  static Color tertiaryBackGroundColor = const Color(0xffE9F4F2);
  static Color cardBackgroundColor = const Color(0xffFFFFFF);
  static Color darkGreyColor = const Color(0xff3A3A3A);
  static Color textColorWhite = const Color(0xffFFFFFF);
  static Color textColorBlack = const Color(0xff000000);
  static Color errorToastBgColor = const Color(0xffFEDAD8);
  static Color successToastBgColor = const Color(0xffC5F8EF);
  static Color successToastTextBlack = const Color(0xff062822);
  static Color shimmerBaseColor = const Color(0xffF1EFEF);
  static Color shimmerHighlightColor = const Color(0xffE7E5E5);
  static Color transparentColor = const Color(0xffFFFFFF);
  static Color borderColor = const Color(0xff041629);
  static Color greenColor = const Color(0xff008A75);
  static Color green8 = const Color(0xff006358);
  static Color lightPinkColor = const Color(0xffF597B9);
  static Color purpleColor = const Color(0xff68378B);
  static Color yellowColor = const Color(0xffFFD35D);
  static Color lightRedColor = const Color(0xffBF4A3F);
  static Color darkGreen = const Color(0xff006358);
  static Color dividerColor = const Color(0xffE9F4F2);
  static Color chipColor = const Color(0xffEDEFEF);
}
